export const PAYMENT= 'PAYMENT';
export const VERIFYPAYMENT = 'VERIFYPAYMENT';
export const REQUEST_PAYMENT='REQUEST_PAYMENT';


export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const VERIFYPAYMENT_FAIL='VERIFYPAYMENT_FAIL';
