export const REGISTER_USER="REGISTER_USER";
export const LOGIN_USER="LOGIN_USER";
export const GET_USER="GET_USER";
export const REQUEST_USER="REQUEST_USER";
export const FORGOT_PASSWORD="FORGOT_PASSWORD";
export const GET_PASSWORDRESET="GET_PASSWORDRESET";


export const REGISTER_USER_FAIL= "REGISTER_USER_FAIL";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const GET_USER_FAIL="GET_USER_FAIL";
export const FORGET_PASSWORD_FAIL="FORGET_PASSWORD_FAIL";
export const GET_PASSWORDRESET_FAIL="GET_PASSWORDRESET_FAIL";
